location = /iaslab/compu2/A00405025-api {
    return 301 /iaslab/compu2/A00405025-api/login;
}

location /iaslab/compu2/A00405025-api/api/ {
    proxy_pass http://127.0.0.1:8085/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /iaslab/compu2/A00405025-api/ {
    alias /home/computacion2/sites/A00405025/dist/;
    index index.html;
    try_files $uri $uri/ /iaslab/compu2/A00405025-api/index.html;
}
