spring.application.name=tarea-react-errorcapa8-backend
server.port=8085
server.servlet.context-path=/auth

app.auth.user-email=admin@errorcapa8.com
app.auth.user-password=Admin123*
app.jwt.secret=ErrorCapa8JwtSecretKeyForSpringBootRest2026
app.jwt.expiration-hours=8
app.cors.allowed-origins=http://127.0.0.1:5173,http://localhost:5173
